services:
  db:
    image: mysql/mysql-server:latest
    ports:
      - ${TEST_DB_PORT}:3306
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=${TEST_DB_PASSWORD}
      - MYSQL_DATABASE=${TEST_DB_NAME}
