services:
  db:
    image: mysql/mysql-server:latest
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=test1234!
      - MYSQL_DATABASE=test_database
